"""Add light and fan columns

Revision ID: f80ede534425
Revises: 
Create Date: 2024-03-27 21:25:06.427929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f80ede534425'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_data', sa.Column('light', sa.Boolean(), nullable=True))
    op.add_column('sensor_data', sa.Column('fan', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_data', 'fan')
    op.drop_column('sensor_data', 'light')
    # ### end Alembic commands ###
